wikimedia/wikipediapreview-wordpress

wikipediapreview-wordpress.php
https://phabricator.wikimedia.org/T279523
Just enough to be recognized as a plugin by WordPress
=> Plugin skeleton

.gitignore, README.md, assets/js/init.js, package-lock.json, package.json, scripts/postinstall.sh, wikipediapreview-wordpress.php
Reverts wikimedia/wikipediapreview-wordpress#4
=> Revert "Revert "T280000 Plugin detect links""

package.json
=> update package.json version to 1.0.2

src/link/inline.js, src/link/style.scss
Phabricator Ticket: https://phabricator.wikimedia.org/T287144
Phabricator Ticket: https://phabricator.wikimedia.org/T290552
Tested on the combination of desktop/mobile, ltr/rtl
| Screenshot 1 | Screenshot 2 |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2560096/136189722-0d63023c-914a-401e-9380-e9ee78373b33.png) | ![image](https://user-images.githubusercontent.com/2560096/136189803-c7438ecc-38d3-4af3-b0e5-723d962b4a65.png) |
=> T287144 T290552 Gutenberg custom format - loading / empty state

src/link/inline.js
Phabricator Link: https://phabricator.wikimedia.org/T294555
Focus search box after text clear
=> T294555 focus input when title clear

readme.txt
https://phabricator.wikimedia.org/T300405
=> Tested with WP 6.0

readme.txt
Found no issues with the plugin on WP 6.1
=> Tested up to: 6.1

banner.php
Phabricator Ticket: https://phabricator.wikimedia.org/T324608
=> T324608 Update Review Banner Copy Text and Styling

src/link/style.scss
https://phabricator.wikimedia.org/T325750
=> Remove outline on preview popup

src/link/inline.js, src/link/preview.js
https://phabricator.wikimedia.org/T327293
=> Replace deprecated anchor ref

readme.txt
https://phabricator.wikimedia.org/T325155
https://phabricator.wikimedia.org/T324596
Update how-to section with better instructions and add "installation" tab with instructions and a repeat of the how-to instructions.
Can't find how to embed images in the instructions. Need to confirm that it's OK without them before merging.
=> Readme install

wikipediapreview.php
https://phabricator.wikimedia.org/T327294
=> Dont include WP on widget page

src/link/inline.js, src/link/preview.js
Phabricator: https://phabricator.wikimedia.org/T325671
use the latest API of `useAnchor` `placement`
=> Update Popover prop of anchor and placement

src/link/inline.js
Phabricator: https://phabricator.wikimedia.org/T325671
remove not necessary prop
=> T325671 remove autofocus prop

readme.txt
Phabrictor Link: https://phabricator.wikimedia.org/T334156
test includes
- w & w/o gutenberg activation
- different themes
=> T334156 Tested up to: 6.2

src/link/inline.js, src/link/style.scss
https://phabricator.wikimedia.org/T295988 
Bye beta
=> Remove beta span

readme.txt
https://phabricator.wikimedia.org/T330531
I added the code snippets between ``` as usual, I guess there's no way to know 100% sure if it will render nicely as expected but it should be okay I think.
=> Add custom css question to FAQ

readme.txt
Phabricator Link: https://phabricator.wikimedia.org/T342512
=> Tested up to: 6.3

readme.txt, src/link/style.scss
Phabricator Link: https://phabricator.wikimedia.org/T340680
additional a quick ui glitch fix
=> Update readme code and ui glitch

src/link/inline.js, src/link/preview.js, src/link/utils.js
Phabricator Link: https://phabricator.wikimedia.org/T343027
=> T343027 - fix preview popup alignment

src/link/style.scss
this is used in the past for older highligh styling
=> remove outdated styling

wikipediapreview.php
https://phabricator.wikimedia.org/T340566
Enable Wikipedia Preview on all post types (build in and custom) marked as "public"
=> Enable Wikipedia Preview on all public post types

wikipediapreview.php
https://phabricator.wikimedia.org/T340566
=> Code cleanup follow up

readme.txt
Phab: https://phabricator.wikimedia.org/T350781
works
=> Tested up to wordpress 6.4

src/link/edit.js
https://phabricator.wikimedia.org/T352873
=> Change position of Wikipedia Preview option on the editing toolbar

readme.txt
Phabricator: https://phabricator.wikimedia.org/T352301
=> Update FQA section and add SEO clarification

src/link/api.js
https://phabricator.wikimedia.org/T355162
=> Add wprov param to track usage of WP search feature in Wordpress

src/link/popover.js
Phab: https://phabricator.wikimedia.org/T365502
test carefully
=> T365502 disable focus on preview popover

src/link/language-selector.js, src/link/style.scss
Phabricator: https://phabricator.wikimedia.org/T366642
=> Fix hidden header in mobile for topic search view

readme.txt
Phab: https://phabricator.wikimedia.org/T368870
=> update screenshot caption

readme.txt
Phabricator: https://phabricator.wikimedia.org/T379710
=> T379710 Tested up to 6.7.1

package-lock.json, package.json
Update to latest version of WP
=> Update version tag of Wikipedia Preview to 1.12.4

package-lock.json, package.json, readme.txt, src/postmeta/wp-postmeta-detectlinks.js
=> Follow up from Adjust PluginDocumentSettingsPanel usage for WP 6.6+ compatibility #141

readme.txt
_Do not merge until all PRs are merged and tested_
=> T396733 Tested up to 6.8.1
