README.md, readme.txt, wikipediapreview.php
- Rename the main plugin file so it doesn't contain "WordPress" (that's not really allowed). When released, the plugin dir will also be just "wikipediapreview" so they will match.
- Add link to privacy policy
- Link to Wikipedia Preview from the readme
- Small wording changes here and there
- Use the version number for the future stable tag. Trunk is not recommended.
=> Fine tuning docs

scripts/zip.sh
It shows silent error here while zip isn't existed, therefore adding force step.
=> Force rm during zip process

assets/js/init.js
how many difference of the content container class name? can it be defined by site owner? or it depends on the theme? check that and confirm before submit the pr to review
=> In some site `entry-content` wasn't found, fallback to document

readme.txt
https://phabricator.wikimedia.org/T285952
Adds the FAQ to our [plugin page](https://wordpress.org/plugins/wikipedia-preview/). I tested with https://wpreadme.com/ (official tool linked from WordPress docs) and also confirmed the correct format by looking at the readme.txt of the example plugin shared in the Phabricator ticket (https://wordpress.org/plugins/wordpress-seo/ -> https://plugins.trac.wordpress.org/browser/wordpress-seo/trunk/readme.txt)
=> T285952: plugin's FAQ

readme.txt
https://phabricator.wikimedia.org/T286941
The WordPress version can be updated from the Dashboard as instructed [here](https://wordpress.org/support/article/updating-wordpress/#one-click-update). Look for the installed version confirmation from either the Dashboard [1] or Local app [2]. 
I tested by creating new separate blog post for both the non-gutenberg version (concerns present PR) and the upcoming gutenberg version (for the future). I followed the regular user flow to create/add Wikipedia Preview to the blog content, tested the preview correctly displaying in Chrome and Firefox. Everything seems to be working fine. 
--- 
_Resources_
https://wordpress.org/support/wordpress-version/version-5-8/
https://make.wordpress.org/core/2021/06/29/block-based-widgets-editor-in-wordpress-5-8/ …
=> T286941: Tested up to WordPress version 5.8

package-lock.json, package.json, src/index.js, src/init.js, src/link/index.js, src/link/utils.js, src/postmeta/index.js, src/postmeta/wp-postmeta-detectlinks.js, wikipediapreview.php
https://phabricator.wikimedia.org/T288570
At the moment, the plugin will use the detect links feature on all posts. However, it may be undesirable on some posts that contain a large number of Wikipedia links where the preview doesn't work (special pages).
In this case, it is better to disable Wikipedia Preview completely on a specific post.
This PR adds a checkbox on the post metadata sidebar to enable/disable Wikipedia Preview just for this post. It is enabled by default.
Also
* Added some unrelated useful commands (check-engines, check-license)
* Made `src/index.js` the single entry point for the editor side
* Moved the feature toggling to js so the postmeta can be enabled but the custom format disabled
=> Allow opt-in/out of detect links feature

readme.txt
Fixes #33 
It replace the WordPress.com link with a link to the CMS docs available here: https://wordpress.org/support/article/paragraph-block/#insert-hyperlinks
=> Replace .com docs with .org

wikipediapreview.php
The widget editor is using Gutenburg so the 'enqueue_block_editor_assets' action runs but it is not appropriate to include the custom format or post meta.
https://phabricator.wikimedia.org/T292634
=> Enqueue the gutenburg custom tools on posts and pages only.

src/link/inline.js, src/link/style.scss
Context here: https://phabricator.wikimedia.org/T287146#7505785
Using the same `languageSelector` state, I realized I could also just switch the main search div on or off, then subsequently realized we could refactor a bit to abstract the `languageSelector` conditional logic to just one instance: within the same inline.js `Popover` we are either showing the language selector UI or the search UI. The benefit of this being that now the dimensions of the language selector can be set without interference. 
This is how I should have done it from the beginning.
=> T287146: language selector follow up

src/link/inline.js, src/link/language-selector.js, src/link/languages.js
https://phabricator.wikimedia.org/T294392
The goal is to allow users to search for langauges using localized strings. That is, if the current user language is english, then typing "hebrew" should render language `he`; if user langauge is spanish, then "hebreo" should render `he`
Is `!! Intl.DisplayNames` an appropriate way to check if the browser supports https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames?
I have tested this in Chrome, Firefox and Safari
=> Add localized languages support

banner.php
When the user dismisses the review banner, we store the value 0 in the wikipediapreview_banner_dismissed property. However, when we read back the property it has the value '0' so it fails the strict comparison to 0.
=> Fix nagging banner

scripts/postinstall.sh
[T329512](https://phabricator.wikimedia.org/T329512)
Adds `.wp-block` selector directly to wikipedia-preview-link.css so that the stylesheet gets correctly picked up by Wordpress and gets injected inside editor. Context: https://github.com/WordPress/gutenberg/issues/41821. I tested by running `npm install` again and confirm the styling shows up after, please take the time to test as well.
=> T329512: Add wordpress class selector

intro.php
https://phabricator.wikimedia.org/T319542
The idea is that after activating the plugin, the intro page will be shown but it won't be permanent under settings menu.  Tested by deactivating and activating the plugin, with and without the Gutenberg plugin activated. You will notice the intro page url will still exist if you navigate away and the press browser back button.
Let's confirm with Sudhanshu before merging, do we need to add the line "Note: These instructions are specifically applicable to the Gutenberg editor" at the end?
=> T319542: Remove submenu page so that it is not permanent

src/link/edit.js
https://phabricator.wikimedia.org/T342838
This approach compares `value` with a previous version of itself to detect relevant edits and remove preview format accordingly. Trimming the format placement is preventive: we don't want untrimmed preview formats for the user to fix in the first place.
=> Remove format on target word edit

wikipediapreview.php
This commit adds a `wikipediapreview:enabled_post_types` filter for extenders who want to tweak the array of post types where the WikiPedia Preview tooltips can be detected. #96
=> Adds filter to update enabled post types

src/postmeta/wp-postmeta-detectlinks.js
https://phabricator.wikimedia.org/T356880
Add guard clause to only show Wikipedia Preview detect links option for post types that support `custom-fields`. Trying to show it for other post types results in an error.
=> Show delete links option only if custom post type supports custom-fields

src/link/edit.js
https://phabricator.wikimedia.org/T355399
Looks like I introduced this bug in https://github.com/wikimedia/wikipediapreview-wordpress/pull/90, there's no need to trim there because text is about to be inserted (trimmed)
=> T355399: Correct values for new text to be inserted

src/link/api.js
https://phabricator.wikimedia.org/T356846
=> Remove disambiguation pages from search results

.eslintrc, .stylelintrc.json, src/link/edit.js, src/link/style.scss, src/link/tooltip.js, tooltip.php, wikipediapreview.php
https://phabricator.wikimedia.org/T352298
Use the Wordpress `Popover` component to fabricate our custom tooltip
=> T352298: Add custom tooltip 

src/link/tooltip.js, tooltip.php
https://phabricator.wikimedia.org/T352298
Follow up to #111, this PR adds the missing `permission_callback` and resolves warnings
=> T352298 follow up: Add missing permission_callback param

src/link/edit.js, src/link/inline.js, src/link/popover.js, src/link/preview.js
https://phabricator.wikimedia.org/T363600
Currently we use the Wordpress `Popover` component in a couple of places: one for `PreviewEditUI` and one for `InlineEditUI`. The bug described in phab above is about the `Popover` not landing correctly to its `anchor` when rapidly switching between `PreviewEditUI` and `InlineEditUI` states. To fix this, I'm proposing refactoring our code to use only a single `Popover` for both states in a new `WikipediaPreviewPopover` component to render the different contents according to the current state. 
While refactoring, I ran into stale closure issues regarding our logic to detect and remove preview formats as the user edits the text. You will notice this by the replacement of `handleTextEdit` with `RemovesPreviewFormat`, for example. Overall, please do …
=> T363600: use a single Popover

src/link/style.scss
https://phabricator.wikimedia.org/T345056#9647116
The preview popover content renders in dark mode (when user setting is detected) because all of that styling comes from the core library. However the actual popover arrow is decoupled from the core library, so we can just style the arrow separately. 
I have added this PR link to https://phabricator.wikimedia.org/T345056#9647116
=> T345056: Update popover arrow style when dark mode is detected

src/link/style.scss
https://phabricator.wikimedia.org/T360750#9856982
In order to avoid the thin line between the popup and the arrow, use the original popover border and overflow the controllers outside using negative margin.
=> Use wordpress popover original border 

src/link/edit.js
https://phabricator.wikimedia.org/T367115
While working on #122, I noticed this bug on main when trying to fix the warning associated with the preview format removal feature. This seems to have been introduced in #116, where a change was made to use `useRef` to keep track of `value` changes. The fix presented here takes the best of the past solutions:
* Keep `valueRef` to keep track of previous value, but simplify as we don't really need `lastValue` state
* Favor `handleTextFormatRemoval` instead of `removesPreviewFormat` as the former is more robust
* This PR also actually fixes the warning that came with the previous solution
Please test carefully
=> T367115: Fix format removal bug

src/link/edit.js
https://phabricator.wikimedia.org/T366873
=> T366873 do not remove preview when W icon is clicked

src/link/sections.js
https://phabricator.wikimedia.org/T360286
This fixes the keyboard navigation bug that Sudhanshu found, testing well for me
=> T360286: Remove onMouseEnter to fix conflict with keyboard navigation

src/link/preview.js, src/link/style.scss
https://phabricator.wikimedia.org/T360753
Update to accommodate for new design layout: https://github.com/wikimedia/wikipedia-preview/pull/218. This comes from a sync with Sudhanshu, we are bringing back the gallery and we're leaving the scroll cue
=> T360753: Update preview layout

src/link/style.scss
Phabricator: https://phabricator.wikimedia.org/T369636
Before
After
After some testing in dark mode and some more tweaking:
=> T369636 Remove min-height and use default height from wordpress popover

.github/workflows/main.yml, src/link/style.scss
https://phabricator.wikimedia.org/T369636
Follow up to #134. [QA feedback pointed](https://phabricator.wikimedia.org/T369636#10310286) to some weird rendering in the corners, after looking very closely I think indeed this `border-radius` is messing with the correct border rendering. 
You really need to get your magnifying glass out to see this one, but I believe this is what was caught by QA:
| with border-radius | without border-radius |
|--------|-------|
| ![Before Image](https://github.com/user-attachments/assets/c1cdf77d-78da-4cab-b406-e1c093d4ace2) | ![After Image](https://github.com/user-attachments/assets/cde7186f-30c6-4a74-9297-fc04f9413b1b) |
| ![Before Image](https://github.com/user-attachments/assets/09183783-a37b-4cf4-89b5-042ee238d45c) | ![After …
=> T369636: Fix border misalignment

.github/workflows/main.yml
This reverts node version back to latest in main workflow file, once the [Webpack issue](https://github.com/webpack/webpack/issues/18963) is resolved. 
Context: https://github.com/wikimedia/wikipediapreview-wordpress/pull/135
=> Set node version to latest
